---
services:
  adminer:
    image: adminer
    restart: no
    ports:
      - 9002:8080
  
  db:
    image: postgres
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pv247-storage-manager
    volumes:
      - ./db:/var/lib/postgresql/data

