---
version: '3.8'
services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9002:8080
  
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: llws
    volumes:
      - ./db:/var/lib/postgresql/data

